---
# tasks file for mapr_cldb_startup

- name: get cluster info
  command: head -1 /opt/mapr/conf/mapr-clusters.conf
  register: this_cluster_conf
  changed_when: false

- name: start warden on CLDBs
  service: name=mapr-warden state=started enabled=yes
  become: yes
  become_user: root
  register: cldb_started
  when: inventory_hostname in groups["cldb"]

- name: wait for MFS to come up
  wait_for: port=5660 timeout=90

- name: let CLDBs have their election and settle
  pause: seconds=45
  when: cldb_started.changed == True
